### ISSUE TITLE
Add yet another view to the Pinged case view. 

### ISSUE THREAD

**Issue by ajockelle** [ITS-Help-Desk/CaseClaim#113]
I'd like to slightly restructure the close/resolve claim process.

1. Bot sends the feedback message with buttons: {Acknowledged}
2. Technician presses Acknowledged
3. Bot @s the lead, then deletes the @ message
4. Add a button to the feedback message with buttons: {Acknowledged, Complete}
5. Lead presses complete, sending them an ephemeral message with all resolving options.

**Comment by AndrewAlbizati** [comment]
Do you think you could elaborate a bit more? I don't think I understand how the ephemeral message would work.

**Comment by Yooply** [comment]
2024 remake

- Bot sends the feedback message with buttons: {Submit}
- Technician presses Submit
- Bot @s the lead, then deletes the @ message, removes the tech from the thread
- Updates the view on the  feedback message with buttons: {Submit(Grayed Out), Complete}
- Lead presses complete, sending them an ephemeral message with all resolving options.

Additionally:

1. clean up the messages - remove messages containing pings, convert all messages to embeds + buttons
2. Once the tech presses Submit  or Acknowledged, the thread disappears for them
